name: Docker CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 3. Log in to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 4. Build, tag, and push docker image to ECR
      - name: Build, tag, and push docker image
        run: |
          IMAGE_URI=730335543972.dkr.ecr.us-east-1.amazonaws.com/node-server:latest
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      # 5. Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 730335543972.dkr.ecr.us-east-1.amazonaws.com
            docker pull 730335543972.dkr.ecr.us-east-1.amazonaws.com/node-server:latest
            docker stop node-server || true
            docker rm node-server || true
            docker run -d --name node-server --network backend -p 3000:3000 730335543972.dkr.ecr.us-east-1.amazonaws.com/node-server:latest
